---
version: "3.1"
services:
  mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    container_name: mastodon
    depends_on:
      - "redis"
      - "database"
      - "mail"
    env_file:
      - ./env/mastodon.env
    volumes:
      - ./letsencrypt/:/etc/letsencrypt/
      - ./conf/mastodon.default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 7080:80
      - 7443:443
    restart: unless-stopped
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mastodon
      POSTGRES_PASSWORD: mastodon
      POSTGRES_DB: mastodon

  mail:
    image: 'namshi/smtp:latest'
    env_file:
      - ./env/mail.env
    ports:
      - 25:25

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - ./env/swag.env
    volumes:
      - ./letsencrypt/:/config/etc/letsencrypt/
      - ./conf/swag.default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
