---
version: "3.1"
services:
  mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    container_name: mastodon
    depends_on:
      - "redis"
      - "database"
      - "mail"
    env_file:
      - openbracket.mastodon.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Halifax

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - DB_HOST=database
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=mastodon
      - DB_PORT=5432

      - ES_ENABLED=false

      - VAPID_PRIVATE_KEY=
      - VAPID_PUBLIC_KEY=

      - SMTP_SERVER=mail
      - SMTP_PORT=25
      - SINGLE_USER_MODE=true
      - DISABLE_IPV6=1

      - S3_ENABLED=false
    volumes:
      - ./letsencrypt/:/etc/letsencrypt/
      - ./default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 7080:80
      - 7443:443
    restart: unless-stopped
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mastodon
      POSTGRES_PASSWORD: mastodon
      POSTGRES_DB: mastodon

  mail:
    image: 'namshi/smtp:latest'
    env_file:
      - openbracket.mail.env
    ports:
      - 25:25

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Halifax
      - URL=openbracket.ca
      - VALIDATION=http
      - EMAIL=bardic.knowledge@gmail.com
      - CERTPROVIDER=zerossl #optional
      - DNSPLUGIN= #optional
      - PROPAGATION= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./letsencrypt/:/config/etc/letsencrypt/
      - ./swag.default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
