---
version: "3.1"
services:
  mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    container_name: mastodon
    depends_on:
      - "redis"
      - "database"
      - "mail"
    env_file:
      - ./env/mastodon.env
    volumes:
      - ./letsencrypt/:/etc/letsencrypt/
      - ./conf/mastodon.default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 7080:80
      - 7443:443
    restart: unless-stopped

  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mastodon
      POSTGRES_PASSWORD: mastodon
      POSTGRES_DB: mastodon

  mail:
    image: 'namshi/smtp:latest'
    env_file:
      - ./env/mail.env
    ports:
      - 25:25

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
